services:
  smartv2xdashboard:
    image: smartv2xdashboard
    build:
      context: dashboard
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
